FROM ubuntu:18.04

# Install keyboard-configuration separately to avoid travis hanging waiting for keyboard selection
RUN \
    apt -y update && \
    apt install -y keyboard-configuration && \

    apt install -y \
        python3-pip \
        python3-dev \
        git && \

    apt clean && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /home

# Cloning the repositories
RUN git clone -b ltldev --single-branch https://github.com/pierg/cogomo.git

# Cloning Strix
RUN git clone https://gitlab.lrz.de/i7/strix.git

RUN python3 -m pip install --user --upgrade pip==9.0.3

RUN \
    pip3 install z3 && \
    pip3 install z3-solver


WORKDIR /home/cogomo

ENV PYTHONPATH "${PYTHONPATH}:/home/cogomo/src"

ENTRYPOINT ["./entrypoint.sh"]
CMD [""]